version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: a4units
    volumes:
      - pgdata:/var/lib/postgresql/data
    labels:
      app: a4units
      role: database

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: adminpass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    labels:
      app: a4units
      role: admin-ui

volumes:
  pgdata:
  pgadmin_data:
